version: '3'
services:
  mongodb_server:
    container_name: mongodb_server
    image: mongo
    command:
      - 'mongod'
      - '-f'
      - '/etc/mongod.conf'
    volumes:
      - './data/mongod.conf:/etc/mongod.conf'
      - './data/db:/data/db'
      - './data/mongod.log:/data/mongod.log'
    ports:
      - '27017:27017'
